---
title: "2020 heat map"
author: "Yiming Li"
output: 
 html_document:
    toc: true
    toc_float: true
---

```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(gganimate)
library(lubridate)
library(plotly)
library(ggthemes)
library(forcats)
library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r, echo = FALSE, message=FALSE,warning = FALSE}
NYPD_2020 = 
  read.csv("../final data/2020data.csv") %>% 
  janitor::clean_names() 
```

```{r, echo = FALSE, message=FALSE,warning = FALSE}
NYPD_2020_day_count = 
  NYPD_2020 %>% 
  filter(name_of_borough != "") %>%  
  group_by(month, day, year) %>% 
  summarise(count = n()) %>% 
  mutate(date = str_c(month, day, year, sep = "/")) %>% 
  mutate(date = mdy(date)) 
```

## 2020 NYPD cluster sum 
```{r}
NYPD_2020_boro = NYPD_2020 %>% 
  filter(name_of_borough != "") 

leaflet(NYPD_2020_boro) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  setView(lng = -73.935242, lat = 40.730610, zoom = 10) %>% 
  addMarkers(clusterOptions = markerClusterOptions())

```

## 2020 NYPD map for five boroughs
```{r}
NYPD_2020  %>% 
  filter(name_of_borough != "") %>% 
  mutate(text_label = str_c("borough:", name_of_borough)) %>% 
  plot_ly()  %>% 
    add_markers(
    y = ~ latitude,
    x = ~ longitude,
    text = ~ text_label,
    alpha = 0.02,
    frame = ~ month,
    mode = "marker",
    color = ~ name_of_borough,
  ) %>%
  animation_opts(transition = 1,frame = 12)
```

## 2020 NYPD day count 

```{r}
plot = 
  NYPD_2020_day_count %>% 
  ggplot(aes(x = date, y = count)) +
  geom_line(col = "deepskyblue3", size = 1) + 
  geom_point(col = "deepskyblue3", size = 2) + 
  labs(title = "Estimated NPYD Count Per Day in 2020",
       subtitle = "1/1/2020 - 12/31/2020.",
       x = "day", 
       y = "Estimated NPYD Xount Per Day") +
  theme(axis.text.x = element_text(angle = 45)) +
  transition_reveal(date) 

plot
```

## Heatmap for 2020 NYPD 

```{r, echo = FALSE, message=FALSE,warning = FALSE}
NYPD_2020_weekdays = 
  NYPD_2020 %>% 
  mutate(date = str_c(month, day, year, sep = "/")) %>% 
  mutate(date = mdy(date)) %>% 
  mutate(dow = wday(date, label = TRUE)) %>% 
  separate(exact_crime_time, into = c("hour", "minute", "second"), sep = ":") %>% 
  group_by(dow, hour) %>% 
  summarise(count = n())
```

```{r}
NYPD_2020_weekdays %>%
  plot_ly(
    x = ~hour, y = ~dow, z = ~count, type = "heatmap", colors = "BuPu"
  ) %>%
  colorbar(title = "2020", x = 1, y = 1) 
```



