---
title: "Regression Analysis"
author: "Wenyu Zhang"
date: "12/9/2021"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(patchwork)
library(MASS)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r, include=FALSE}
dat = read_csv("/Users/wenyuzhang/Desktop/final data/2020data.csv")
head(dat)
```

# Regression Analysis

## Clean and summary data
```{r}
## regression
clean_regression =
  dat %>%
  filter(!(susp_age_group == ""),
         !(susp_race == ""),
         !(susp_sex == ""),
         !(name_of_borough == "")) %>%
  filter(!(susp_age_group == "UNKNOWN"),
         !(susp_race == "UNKNOWN"),
         !(susp_sex == "UNKNOWN"),
         !(susp_sex == "U")) %>%
  filter((susp_age_group == "25-44") | (susp_age_group == "45-64") | (susp_age_group == "18-24") | (susp_age_group == "65+") | (susp_age_group == "<18")) %>%
  mutate(level_of_offense = ordered(level_of_offense, 
                                    levels = c("VIOLATION", 
                                               "MISDEMEANOR", 
                                               "FELONY"))) %>%
  mutate(susp_age_group = as.factor(susp_age_group)) %>%
  mutate(susp_race = as.factor(susp_race)) %>%
  mutate(susp_sex = as.factor(susp_sex))

clean_regression

# run proportional odds model
model <- polr(formula = level_of_offense ~ susp_age_group + susp_race + susp_sex + name_of_borough, data = clean_regression)

# get summary
summary(model)
```

## Proportional Odds Logistic Regression

```{r}
ctable <- coef(summary(model))
## calculate and store p values
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

## combined table
(ctable <- cbind(ctable, "p value" = p))
```
